defaults:
  env:
    AWS_BUCKET: "..."
    AWS_KEY: "..."
    AWS_SECRET: "..."
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sean-doody/start-ira-gptj
  TrainModel:
    resources:
      instance-type: A100-80G
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: huggingface/transformers-pytorch-gpu
      script: |-
        cd /inputs/repo
        pip3 install scikit-learn
        pip3 install tqdm
        pip3 install boto3
        python3 train.py