defaults:
  env:
    AWS_BUCKET: "ira-pres-tweets"
    AWS_KEY: "AKIATC4N657YKPB3GFXC"
    AWS_SECRET: "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"
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sean-doody/start-ira-gptj
  TrainModel:
    resources:
      instance-type: A100-80G
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: huggingface/transformers-pytorch-gpu
      script: |-
        cd /inputs/repo
        pip3 install --upgrade pip
        pip3 install deepspeed
        pip3 install tqdm
        pip3 install sklearn
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
        pip3 install -U transformers
        pip3 install boto3
        python3 train.py
        cp -r ./trained-model /outputs/trained-model
    outputs:
      gpt-j-01:
        type: dataset
        with:
          ref: dsknpm89xo6gi7o
  SaveModel:
    uses: create-model@v1
    resources:
      instance-type: C5
    with: 
      name: gpt-j-01
      type: Custom
    needs:
      - TrainModel
    inputs:
      model: TrainModel.outputs.gpt-j-01
    outputs:
      model-id:
        type: string